In [1]:
import pandas as pd
import numpy as np

# Phase 1 : Preparing core data

In [2]:
df = pd.read_csv('elections.csv')

In [3]:
df.sample(10)

,Unnamed: 0,Code département,département,Inscrits,Votants,Blancs et nuls,Exprimés,year,election_round,election
12626,12626,55,MEUSE,3870,2555,118,2437,2004,t1,cantonales
12107,12107,30,GARD,8756,6284,219,6065,2004,t1,cantonales
18912,18912,68,HAUT-RHIN,71589,33389,4197,29192,2002,t2,legislative
7117,7117,17,CHARENTE MARITIME,8039,5538,323,5215,2004,t2,cantonales
11276,11276,87,HAUTE VIENNE,4606,3029,238,2791,2008,t1,cantonales
5459,5459,10,AUBE,5766,3352,209,3143,2011,t2,cantonales
10794,10794,63,PUY DE DOME,4332,3585,144,3441,2008,t1,cantonales
2386,2386,54,MEURTHE ET MOSELLE,7565,3674,95,3579,2011,t1,cantonales
10328,10328,42,LOIRE,18898,10683,287,10396,2008,t1,cantonales
11035,11035,74,HAUTE SAVOIE,33199,19628,590,19038,2008,t1,cantonales

In [4]:
#df['Code département'].drop_duplicates().tolist()

In [24]:
def apply_region (row):
    if (row['Code département'] in ['67','68']):
        val = 'Grand Est'
    elif (row['Code département'] in ['24','33','40','47','64']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['3','15','43','63']):
        val = 'Auvergne-Rhône-Alpes'
    elif (row['Code département'] in ['14','50','61']):
        val = 'Normandie'
    elif (row['Code département'] in ['21','58','71','89']):
        val = 'Bourgogne-Franche-Comté'
    elif (row['Code département'] in ['22','29','35','56']):
        val = 'Bretagne'
    elif (row['Code département'] in ['18','24','36','37','41','45']):
        val = 'Centre-Val-de-Loire'
    elif (row['Code département'] in ['8','10','51','52']):
        val = 'Grand Est'
    elif (row['Code département'] in ['2A','2B']):
        val = 'Corse'
    elif (row['Code département'] in ['25','39','70','90']):
        val = 'Bourgogne-Franche-Comté'
    elif (row['Code département'] in ['27','76']):
        val = 'Normandie'
    elif (row['Code département'] in ['75','77','78','91','92','93','94','95']):
        val = 'Île-de-France'
    elif (row['Code département'] in ['11','30','34','48','66']):
        val = 'Occitanie'
    elif (row['Code département'] in ['19','23','87']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['54','55','57','88']):
        val = 'Grand Est'
    elif (row['Code département'] in ['9','12','31','32','46','65','81','82']):
        val = 'Occitanie'
    elif (row['Code département'] in ['44','49','53','72','85']):
        val = 'Pays de la Loire'
    elif (row['Code département'] in ['2','60','80']):
        val = 'Hauts-de-France'
    elif (row['Code département'] in ['59','62']):
        val = 'Hauts-de-France'
    elif (row['Code département'] in ['16','17','79','86']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['4','5','6','13','83','84']):
        val = "Provence-Alpes-Côte d'Azur"
    elif (row['Code département'] in ['1','7','26','38','42','69','73','74']):
        val = 'Auvergne-Rhône-Alpes'
    elif (row['Code département'] in ['971']):
        val = 'Guadeloupe '
    elif (row['Code département'] in ['972']):
        val = 'Martinique '
    elif (row['Code département'] in ['973']):
        val = 'Guyane'
    elif (row['Code département'] in ['974']):
        val = 'La Réunion'
    elif (row['Code département'] in ['976']):
        val = 'Mayotte'
    elif (row['Code département'] in ['984','986','987','988','975']):
        val = 'DOM'
    else :
        val = 'no region'
    return val

In [25]:
df['region'] = df.apply(apply_region, axis=1)

In [26]:
df.region.drop_duplicates().tolist()

['Auvergne-Rhône-Alpes',
 'Hauts-de-France',
 "Provence-Alpes-Côte d'Azur",
 'Grand Est',
 'Occitanie',
 'Normandie',
 'Nouvelle-Aquitaine',
 'Centre-Val-de-Loire',
 'Corse',
 'Bourgogne-Franche-Comté',
 'Bretagne',
 'no region',
 'Pays de la Loire',
 'Île-de-France',
 'Guadeloupe ',
 'Martinique ',
 'Guyane',
 'La Réunion',
 'DOM']

In [31]:
df_tmp = df.groupby(['region', 'year', 'election'])['Votants'].mean()

In [32]:
df_new = pd.DataFrame(df_tmp).reset_index()

In [33]:
df_new

                   region  year      election       Votants
0    Auvergne-Rhône-Alpes  2001    cantonales   5890.409412
1    Auvergne-Rhône-Alpes  2002   legislative  46230.082645
2    Auvergne-Rhône-Alpes  2002  presidential  57294.349206
3    Auvergne-Rhône-Alpes  2004    cantonales   6461.525727
4    Auvergne-Rhône-Alpes  2007   legislative  47052.491071
..                    ...   ...           ...           ...
181         Île-de-France  2007  presidential  57991.075758
182         Île-de-France  2008    cantonales  10072.592885
183         Île-de-France  2011    cantonales   7147.654605
184         Île-de-France  2012   legislative  39566.901554
185         Île-de-France  2012  presidential  57026.092784

[186 rows x 4 columns]

# Phase 2 : Join/Merge

In [56]:
df_men = pd.read_csv('study_men.csv')
df_women = pd.read_csv('study_women.csv')

In [57]:
df_men.shape

(324, 5)

In [58]:
df_women.shape

(324, 5)

In [62]:
df_genders = pd.merge(df_men, df_women, on=['year','region'])
df_genders.drop(columns=['Unnamed: 0_x', 'gender_x', 'gender_y', 'Unnamed: 0_y'], inplace=True)

In [63]:
df_genders

     year                      region  total_men  total_women
0    2002        Auvergne-Rhône-Alpes    3464799      3651145
1    2002     Bourgogne-Franche-Comté    1341369      1408523
2    2002                    Bretagne    1447224      1534541
3    2002         Centre-Val-de-Loire    1204878      1268100
4    2002                       Corse     133448       140645
..    ...                         ...        ...          ...
319  2017          Nouvelle-Aquitaine    2868828      3088150
320  2017                   Occitanie    2823736      3021366
321  2017            Pays de la Loire    1829677      1927923
322  2017  Provence-Alpes-Côte d'Azur    2405990      2624900
323  2017               Île-de-France    5874565      6300315

[324 rows x 4 columns]

In [69]:
df_join = pd.merge(df_genders, df_new, on=['region', 'year'])
df_join['Metric'] = 'Gender'
df_join

,year,region,total_men,total_women,election,Votants,Metric
0,2002,Auvergne-Rhône-Alpes,3464799,3651145,legislative,46230.082645,Gender
1,2002,Auvergne-Rhône-Alpes,3464799,3651145,presidential,57294.349206,Gender
2,2002,Bourgogne-Franche-Comté,1341369,1408523,legislative,40952.192982,Gender
3,2002,Bourgogne-Franche-Comté,1341369,1408523,presidential,49786.283333,Gender
4,2002,Bretagne,1447224,1534541,legislative,55924.687500,Gender
...,...,...,...,...,...,...,...
154,2012,Pays de la Loire,1769777,1862837,presidential,72943.166667,Gender
155,2012,Provence-Alpes-Côte d'Azur,2360622,2574954,legislative,46663.390244,Gender
156,2012,Provence-Alpes-Côte d'Azur,2360622,2574954,presidential,66196.535714,Gender
157,2012,Île-de-France,5746662,6151840,legislative,39566.901554,Gender
158,2012,Île-de-France,5746662,6151840,presidential,57026.092784,Gender

In [70]:
#df_join.to_csv('gender.csv', index=False)