In [1]:
import pandas as pd
import numpy as np

# Phase 1 : Preparing core data

In [2]:
df = pd.read_csv('elections.csv')

In [3]:
df.sample(10)

,Unnamed: 0,Code département,département,Inscrits,Votants,Blancs et nuls,Exprimés,year,election_round,election
6988,6988,6,ALPES MARITIMES,19006,11327,289,11038,2004,t2,cantonales
6032,6032,45,LOIRET,13772,6126,512,5614,2011,t2,cantonales
12252,12252,36,INDRE,5085,3598,146,3452,2004,t1,cantonales
17010,17010,2,AISNE,73010,47915,861,47054,2002,t1,legislative
8174,8174,83,VAR,33091,21439,533,20906,2004,t2,cantonales
19991,19991,60,OISE,73674,44489,839,43650,2007,t1,legislative
15289,15289,4,ALPES-DE-HAUTE-PROVENCE,60587,50916,3477,47439,2012,t2,presidential
13202,13202,82,TARN ET GARONNE,4829,3570,210,3360,2004,t1,cantonales
7969,7969,70,HAUTE SAONE,9006,6319,357,5962,2004,t2,cantonales
4838,4838,73,SAVOIE,4362,3196,126,3070,2001,t1,cantonales

In [4]:
#df['Code département'].drop_duplicates().tolist()

In [5]:
def apply_region (row):
    if (row['Code département'] in ['67','68']):
        val = 'Grand Est'
    elif (row['Code département'] in ['24','33','40','47','64']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['3','15','43','63']):
        val = 'Auvergne-Rhône-Alpes'
    elif (row['Code département'] in ['14','50','61']):
        val = 'Normandie'
    elif (row['Code département'] in ['21','58','71','89']):
        val = 'Bourgogne-Franche-Comté'
    elif (row['Code département'] in ['22','29','35','56']):
        val = 'Bretagne'
    elif (row['Code département'] in ['18','24','36','37','41','45']):
        val = 'Centre-Val-de-Loire'
    elif (row['Code département'] in ['8','10','51','52']):
        val = 'Grand Est'
    elif (row['Code département'] in ['2A','2B']):
        val = 'Corse'
    elif (row['Code département'] in ['25','39','70','90']):
        val = 'Bourgogne-Franche-Comté'
    elif (row['Code département'] in ['27','76']):
        val = 'Normandie'
    elif (row['Code département'] in ['75','77','78','91','92','93','94','95']):
        val = 'Île-de-France'
    elif (row['Code département'] in ['11','30','34','48','66']):
        val = 'Occitanie'
    elif (row['Code département'] in ['19','23','87']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['54','55','57','88']):
        val = 'Grand Est'
    elif (row['Code département'] in ['9','12','31','32','46','65','81','82']):
        val = 'Occitanie'
    elif (row['Code département'] in ['44','49','53','72','85']):
        val = 'Pays de la Loire'
    elif (row['Code département'] in ['2','60','80']):
        val = 'Hauts-de-France'
    elif (row['Code département'] in ['59','62']):
        val = 'Hauts-de-France'
    elif (row['Code département'] in ['16','17','79','86']):
        val = 'Nouvelle-Aquitaine'
    elif (row['Code département'] in ['4','5','6','13','83','84']):
        val = "Provence-Alpes-Côte d'Azur"
    elif (row['Code département'] in ['1','7','26','38','42','69','73','74']):
        val = 'Auvergne-Rhône-Alpes'
    elif (row['Code département'] in ['971']):
        val = 'Guadeloupe '
    elif (row['Code département'] in ['972']):
        val = 'Martinique '
    elif (row['Code département'] in ['973']):
        val = 'Guyane'
    elif (row['Code département'] in ['974']):
        val = 'La Réunion'
    elif (row['Code département'] in ['976']):
        val = 'Mayotte'
    elif (row['Code département'] in ['984','986','987','988','975']):
        val = 'DOM'
    else :
        val = 'no region'
    return val

In [6]:
df['region'] = df.apply(apply_region, axis=1)

In [7]:
df.region.drop_duplicates().tolist()

['Auvergne-Rhône-Alpes',
 'Hauts-de-France',
 "Provence-Alpes-Côte d'Azur",
 'Grand Est',
 'Occitanie',
 'Normandie',
 'Nouvelle-Aquitaine',
 'Centre-Val-de-Loire',
 'Corse',
 'Bourgogne-Franche-Comté',
 'Bretagne',
 'no region',
 'Pays de la Loire',
 'Île-de-France',
 'Guadeloupe ',
 'Martinique ',
 'Guyane',
 'La Réunion',
 'DOM']

In [8]:
df

,Unnamed: 0,Code département,département,Inscrits,Votants,Blancs et nuls,Exprimés,year,election_round,election,region
0,0,1,AIN,12513,6169,598,5571,2001,t2,cantonales,Auvergne-Rhône-Alpes
1,1,1,AIN,8358,4793,249,4544,2001,t2,cantonales,Auvergne-Rhône-Alpes
2,2,1,AIN,2619,1852,94,1758,2001,t2,cantonales,Auvergne-Rhône-Alpes
3,3,1,AIN,5830,3847,140,3707,2001,t2,cantonales,Auvergne-Rhône-Alpes
4,4,1,AIN,3592,2304,181,2123,2001,t2,cantonales,Auvergne-Rhône-Alpes
...,...,...,...,...,...,...,...,...,...,...,...
20258,20258,986,WALLIS ET FUTUNA,11160,7849,65,7784,2007,t1,legislative,DOM
20259,20259,987,POLYNESIE FRANCAISE,93813,52894,413,52481,2007,t1,legislative,DOM
20260,20260,987,POLYNESIE FRANCAISE,73916,39222,408,38814,2007,t1,legislative,DOM
20261,20261,988,NOUVELLE-CALEDONIE,68940,37863,808,37055,2007,t1,legislative,DOM
20262,20262,988,NOUVELLE-CALEDONIE,69695,37001,1242,35759,2007,t1,legislative,DOM

In [9]:
df_tmp = df.groupby(['region', 'year', 'election', 'département'])['Votants'].mean()
df_new = pd.DataFrame(df_tmp).reset_index()

In [10]:
df_new

,region,year,election,département,Votants
0,Auvergne-Rhône-Alpes,2001,cantonales,AIN,4526.027027
1,Auvergne-Rhône-Alpes,2001,cantonales,ALLIER,4930.967742
2,Auvergne-Rhône-Alpes,2001,cantonales,ARDECHE,5403.750000
3,Auvergne-Rhône-Alpes,2001,cantonales,CANTAL,3663.705882
4,Auvergne-Rhône-Alpes,2001,cantonales,DROME,5424.242424
...,...,...,...,...,...
1072,Île-de-France,2012,presidential,SEINE-ET-MARNE,60773.409091
1073,Île-de-France,2012,presidential,SEINE-SAINT-DENIS,46266.791667
1074,Île-de-France,2012,presidential,VAL-D'OISE,55350.850000
1075,Île-de-France,2012,presidential,VAL-DE-MARNE,55127.227273
1076,Île-de-France,2012,presidential,YVELINES,62199.333333

In [11]:
df_tmp = df_new.groupby(['region', 'year', 'election'])['Votants'].sum()
df_new = pd.DataFrame(df_tmp).reset_index()

In [12]:
df_new

                   region  year      election        Votants
0    Auvergne-Rhône-Alpes  2001    cantonales   67328.644670
1    Auvergne-Rhône-Alpes  2002   legislative  570620.628205
2    Auvergne-Rhône-Alpes  2002  presidential  702293.197222
3    Auvergne-Rhône-Alpes  2004    cantonales   72414.786690
4    Auvergne-Rhône-Alpes  2007   legislative  580283.554981
..                    ...   ...           ...            ...
181         Île-de-France  2007  presidential  775287.998199
182         Île-de-France  2008    cantonales   71310.161214
183         Île-de-France  2011    cantonales   49970.992713
184         Île-de-France  2012   legislative  316425.358966
185         Île-de-France  2012  presidential  456844.970338

[186 rows x 4 columns]

# Phase 2 : Join/Merge

In [21]:
df_men = pd.read_csv('study_men.csv')
df_women = pd.read_csv('study_women.csv')
df_all_salary = pd.read_csv('pop-salary-contribution.csv')

In [22]:
df_all_salary.region.drop_duplicates().tolist()

['Auvergne-Rhône-Alpes',
 'Bourgogne-Franche-Comté',
 'Bretagne',
 'Centre-Val-de-Loire',
 'Corse',
 'Grand Est',
 'Hauts-de-France',
 'Île-de-France',
 'Normandie',
 'Nouvelle-Aquitaine',
 'Occitanie',
 'Pays de la Loire',
 "Provence-Alpes-Côte d'Azur",
 'France métropolitaine',
 'DOM',
 'Guadeloupe ',
 'Martinique ',
 'Guyane',
 'La Réunion',
 'Mayotte']

In [23]:
df_genders = pd.merge(df_men, df_women, on=['year','region'])
df_genders.drop(columns=['Unnamed: 0_x', 'gender_x', 'gender_y', 'Unnamed: 0_y'], inplace=True)

In [25]:
df_test = pd.merge(df_new, df_all_salary, on=['year','region'])
df_test.drop(columns=['Unnamed: 0'], inplace=True)
df_test['Metric'] = 'Salary'
#df_test.to_csv('salary-contribution.csv', index=False)
df_test

,region,year,election,Votants,social-contribution,gross-salary,Total,Metric
0,Auvergne-Rhône-Alpes,2002,legislative,5.706206e+05,1611.0,16411.0,7115944,Salary
1,Auvergne-Rhône-Alpes,2002,presidential,7.022932e+05,1611.0,16411.0,7115944,Salary
2,Auvergne-Rhône-Alpes,2004,cantonales,7.241479e+04,1734.0,17344.0,7231833,Salary
3,Auvergne-Rhône-Alpes,2007,legislative,5.802836e+05,1928.0,19295.0,7405206,Salary
4,Auvergne-Rhône-Alpes,2007,presidential,1.051058e+06,1928.0,19295.0,7405206,Salary
...,...,...,...,...,...,...,...,...
154,Île-de-France,2007,presidential,7.752880e+05,2900.0,23194.0,11598866,Salary
155,Île-de-France,2008,cantonales,7.131016e+04,2878.0,23535.0,11659260,Salary
156,Île-de-France,2011,cantonales,4.997099e+04,2950.0,24138.0,11852851,Salary
157,Île-de-France,2012,legislative,3.164254e+05,3038.0,24200.0,11898502,Salary
158,Île-de-France,2012,presidential,4.568450e+05,3038.0,24200.0,11898502,Salary

In [63]:
df_genders

     year                      region  total_men  total_women
0    2002        Auvergne-Rhône-Alpes    3464799      3651145
1    2002     Bourgogne-Franche-Comté    1341369      1408523
2    2002                    Bretagne    1447224      1534541
3    2002         Centre-Val-de-Loire    1204878      1268100
4    2002                       Corse     133448       140645
..    ...                         ...        ...          ...
319  2017          Nouvelle-Aquitaine    2868828      3088150
320  2017                   Occitanie    2823736      3021366
321  2017            Pays de la Loire    1829677      1927923
322  2017  Provence-Alpes-Côte d'Azur    2405990      2624900
323  2017               Île-de-France    5874565      6300315

[324 rows x 4 columns]

In [69]:
df_join = pd.merge(df_genders, df_new, on=['region', 'year'])
df_join['Metric'] = 'Gender'
df_join

,year,region,total_men,total_women,election,Votants,Metric
0,2002,Auvergne-Rhône-Alpes,3464799,3651145,legislative,46230.082645,Gender
1,2002,Auvergne-Rhône-Alpes,3464799,3651145,presidential,57294.349206,Gender
2,2002,Bourgogne-Franche-Comté,1341369,1408523,legislative,40952.192982,Gender
3,2002,Bourgogne-Franche-Comté,1341369,1408523,presidential,49786.283333,Gender
4,2002,Bretagne,1447224,1534541,legislative,55924.687500,Gender
...,...,...,...,...,...,...,...
154,2012,Pays de la Loire,1769777,1862837,presidential,72943.166667,Gender
155,2012,Provence-Alpes-Côte d'Azur,2360622,2574954,legislative,46663.390244,Gender
156,2012,Provence-Alpes-Côte d'Azur,2360622,2574954,presidential,66196.535714,Gender
157,2012,Île-de-France,5746662,6151840,legislative,39566.901554,Gender
158,2012,Île-de-France,5746662,6151840,presidential,57026.092784,Gender

In [70]:
#df_join.to_csv('gender.csv', index=False)